packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@prisma/engines': true
  '@sentry/cli': true
  '@sentry/node-cpu-profiler': false
  bcrypt: true
  esbuild: true
  msgpackr-extract: true
  msw: false
  prisma: true
  protobufjs: true
  sharp: true
  unrs-resolver: false
overrides:
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
