apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    isDefault: false
    editable: false
    jsonData:
      httpMethod: GET
      nodeGraph:
        enabled: true
      tracesToMetrics:
        datasourceUid: prometheus
        tags: [{ key: 'service.name', value: 'service' }, { key: 'job' }]
        queries:
          - name: 'Request rate'
            query: 'sum(rate(http_requests_total{$$__tags}[5m]))'
          - name: 'Error rate'
            query: 'sum(rate(http_requests_total{status=~"5..", $$__tags}[5m]))'
          - name: 'Latency (p95)'
            query: 'histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{$$__tags}[5m])) by (le))'
